leadmanger/djangogram/djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"

# views에서 main함수 호출
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

leadmanger/leadmanger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls'))
]

leadmanger/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout",views.logout_view, name="logout"),
    path("singup", views.signup_view, name="signup")
]

leadmanger/djangogram/djangogram/users/models.py
from typing import BinaryIO
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import get_supported_language_variant, gettext_lazy as _


class User(AbstractUser):
    """Default user for djangogram."""

    # (DB저장값, 사용자입력값)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom'),
    ]
    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    # 사용자 이름 : char형(빈칸 가능, 최대 글자수가 255)
    user_name = models.CharField(blank=True, max_length=255)

    # 프로필 사진 : image형
    profile_photo = models.ImageField(blank=True)

    # 웹사이트 : url형 
    website = models.URLField(blank=True)

    # 소개 : text형
    bio = models.TextField(blank=True)

    # 이메일 : char형
    email = models.CharField(blank=True, max_length=255)

    # 전화번호 : char형
    phone_number = models.CharField(blank=True, max_length=255)

    # 성별 : char형(chice를 사용하여 특정값만 입력되도록)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)

    # 팔로워(다대다관계)
    followers = models.ManyToManyField("self")
    # 팔로잉(다대다관계)
    following = models.ManyToManyField("self")

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

leadmanger/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    student_id = models.CharField(max_length=10)

leadmanger/djangogram/djangogram/users/forms.py
import django
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']
        
        labels = {
            'email' : '',
            'name' : '',
            'username' : '',
            'password' : '',
        }
    
        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder':'이메일주소', 'class':'name-class'}),
            'name': django_forms.TextInput(attrs={'placeholder':'성명', 'class':'name-class'}),
            'username': django_forms.TextInput(attrs={'placeholder':'사용자이름', 'class':'name-class'}),
            'password': django_forms.PasswordInput(attrs={'placeholder':'비밀번호', 'class':'name-class'}),
        }

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

leadmanger/djangogram/djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login

from .forms import SignUpForm

# users app - login 
def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('posts:index'))
        else:
            return render(request, 'users/main.html')        

def signup(request):
    # 화면 요청 GET
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form': form})
    
    # 회원가입 요청 POST
    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid:
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('posts:index'))
            
        return render(request, 'users/main.html')

leadmanger/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from .models import User

# Create your views here.
@csrf_exempt
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증 성공")
            login(request, user)
        else:
            print("인증 실패")
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]
        
        user = User.objects.create_user(username, email, password)
        user.firstname = firstname
        user.lastname = lastname
        user.student_id = student_id
        user.save()
        return redirect("user:login")
        

    return render(request, "users/signup.html")
#if request.method == "POST":
#        print(request.POST)
"""
username = request.POST["username"]
        password = request.POST["password"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]
        
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.student_id = student_id
        user.save()
        return redirect("user:login")
"""

leadmanger/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN</title>
    <script>
        $.ajaxSetup({
          headers: { "X-CSRFToken": '{{ csrf_token }}' }
        });
    </script>
    {% load static %}
    <link rel="stylesheet"  type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
    {% csrf_token %}
    
    {% if user.is_authenticated %}
    
    <!-- 로그인 성공하면 로그아웃도 가능. -->
    <from class="success" action="" method="POST">
        <h1>로그인 성공</h1>
        <h1>{{ user.username }}님 환영합니다.</h1>
        <a href="{% url 'user:logout' %}">로그아웃</a>
    </from>

    {% else %}
    <form class="box" action="" method="POST">
        <h1>LOGIN</h1>
        
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" name="loginButton" value="LOGIN">
        <a href="{% url 'user:signup' %}">회원가입</a>
    </form>
    
    {% endif %}


</body>
</html>

<!--
    <button type="button" name="new" onClick="location.href='register.php'">회원가입</button>
    <link rel="stylesheet" href="styles.css">
    {% csrf_token %}
    --->

leadmanger/users/templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>REGISTER</title>
    {% load static %}
    <link rel="stylesheet"  type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>

    <form class="box" action="" method="POST">
        {% csrf_token %}
        <h1>회원가입</h1>
        
        <label>아이디</label>
        <input type="text" name="username" placeholder="Username">
        <label>비밀번호</label>
        <input type="text" name="password" placeholder="Password">
        <label>성</label>
        <input type="text" name="firstname" placeholder="first_name">
        <label>이름</label>
        <input type="text" name="lastname" placeholder="last_name">
        <label>이메일</label>
        <input type="text" name="email" placeholder="email">
        <label>학번</label>
        <input type="text" name="student_id" placeholder="student_id">

        <input type="submit" name="registerButton" value="회원가입">
    </form>

</body>
</html>