leadmanger/djangogram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # root url path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("djangogram.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # root url 이 users이 되도록 -> users앱 url에서 설정
    # /
    path("", include("djangogram.users.urls", namespace="users")),

    # /post/
    path("posts/", include("djangogram.posts.urls", namespace="posts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

leadmanger/djangogram/djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
]

leadmanger/djangogram/djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"

# views에서 main함수 호출
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

leadmanger/leadmanger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls'))
]

leadmanger/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout",views.logout_view, name="logout"),
    path("singup", views.signup_view, name="signup")
]

leadmanger/djangogram/djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model 

# Create your models here.

# 시간 관리(업로드 업데이트 날짜) - 상속
class TimeStamedModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    upadte_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

# 사진 관리
class Post(TimeStamedModel):
    # 작성자 (users모델의 user - 외래키)
    author = models.ForeignKey(
                user_model.User, 
                null=True,
                on_delete=models.CASCADE,
                related_name='post_author'
            )
    # 사진
    image = models.ImageField(blank=True)
    # 캡션
    cpation = models.TextField(blank=True)
    # 좋아요(다대다 관계)
    image_likes = models.ManyToManyField(user_model.User, related_name='post_image_likes')


# 댓글 관리
class Comment(TimeStamedModel):
    # 작성자
    author = models.ForeignKey(
                user_model.User,
                null=True, 
                on_delete=models.CASCADE, 
                related_name='comment_author'
            )
    # 포스트
    posts = models.ForeignKey(
                Post,
                null=True, 
                on_delete=models.CASCADE, 
                related_name='comment_post'
            )
    # 댓글 내용
    contents = models.TextField(blank=True)

leadmanger/djangogram/djangogram/users/models.py
from typing import BinaryIO
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import get_supported_language_variant, gettext_lazy as _


class User(AbstractUser):
    """Default user for djangogram."""

    # (DB저장값, 사용자입력값)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom'),
    ]
    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    # 사용자 이름 : char형(빈칸 가능, 최대 글자수가 255)
    user_name = models.CharField(blank=True, max_length=255)

    # 프로필 사진 : image형
    profile_photo = models.ImageField(blank=True)

    # 웹사이트 : url형 
    website = models.URLField(blank=True)

    # 소개 : text형
    bio = models.TextField(blank=True)

    # 이메일 : char형
    email = models.CharField(blank=True, max_length=255)

    # 전화번호 : char형
    phone_number = models.CharField(blank=True, max_length=255)

    # 성별 : char형(chice를 사용하여 특정값만 입력되도록)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)

    # 팔로워(다대다관계)
    followers = models.ManyToManyField("self")
    # 팔로잉(다대다관계)
    following = models.ManyToManyField("self")

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

leadmanger/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    student_id = models.CharField(max_length=10)

leadmanger/djangogram/djangogram/users/forms.py
import django
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']
        
        labels = {
            'email' : '',
            'name' : '',
            'username' : '',
            'password' : '',
        }
    
        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder':'이메일주소', 'class':'name-class'}),
            'name': django_forms.TextInput(attrs={'placeholder':'성명', 'class':'name-class'}),
            'username': django_forms.TextInput(attrs={'placeholder':'사용자이름', 'class':'name-class'}),
            'password': django_forms.PasswordInput(attrs={'placeholder':'비밀번호', 'class':'name-class'}),
        }

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

leadmanger/djangogram/djangogram/posts/views.py
from django.shortcuts import render

# Create your views here.
# posts app - login success
def index(request):
    return render(request, 'posts/index.html')

leadmanger/djangogram/djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login

from .forms import SignUpForm

# users app - login 
def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('posts:index'))
        else:
            return render(request, 'users/main.html')        

def signup(request):
    # 화면 요청 GET
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form': form})
    
    # 회원가입 요청 POST
    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid:
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('posts:index'))
            
        return render(request, 'users/main.html')

leadmanger/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from .models import User

# Create your views here.
@csrf_exempt
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        if user is not None:
            print("인증 성공")
            login(request, user)
        else:
            print("인증 실패")
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]
        
        user = User.objects.create_user(username, email, password)
        user.firstname = firstname
        user.lastname = lastname
        user.student_id = student_id
        user.save()
        return redirect("user:login")
        

    return render(request, "users/signup.html")
#if request.method == "POST":
#        print(request.POST)
"""
username = request.POST["username"]
        password = request.POST["password"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        email = request.POST["email"]
        student_id = request.POST["student_id"]
        
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.student_id = student_id
        user.save()
        return redirect("user:login")
"""

leadmanger/djangogram/djangogram/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}Instagram</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/main.css' %}">
</head>
<body>
    <!-- content -->
    <div class="form-content">
        <img class="img-logo" src="{% static 'images/logo.png' %}" alt="logo">
        {% block content %} {% endblock %}
    </div>

    <div class="form-link">
        {% block link %} {% endblock %}
    </div>
    
    <!-- footer -->
    <div class="footer-class">
        {% include "users/footer.html" %}
    </div>
</body>
</html>

leadmanger/djangogram/djangogram/templates/users/footer.html
<a href="#">소개</a>
<a href="#">블로그</a>
<a href="#">채용 정보</a>
<a href="#">도움말</a>
<a href="#">API</a>
<a href="#">개인정보처리방침</a>
<a href="#">약관</a>
<a href="#">인기 계정</a>
<a href="#">해시태그</a>
<a href="#">위치</a>

leadmanger/djangogram/djangogram/templates/users/main.html
{% extends "users/base.html" %}

{% block title %}
Iogin
{% endblock title %}


<h1>login page</h1>    
{% block content %}
<form action="{% url 'users:main' %}" method='post'>
    {% csrf_token %}
    <input class="name-class" type="text" name="username" placeholder="사용자이름 또는 이메일"></input>
    <input class="password-class" type="password" name="password" placeholder="비밀번호"></input>
    <input class="submit-class" type="submit" value="로그인"></input>
</form>
{% endblock content %}

{% block link %}
계정이 없으신가요? <a href="{% url 'users:signup' %}">가입하기</a>
{% endblock link %}

leadmanger/djangogram/djangogram/templates/users/signup.html
{% extends "users/base.html" %}

{% block title %}
SignUp
{% endblock title %}
{% block content %}
<form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    <div class="text-label">친구들의 사진과 동영상을 보려면 가입하세요.</div>
    {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <input class="submit-class" type="submit" value="가입">
</form>

{% endblock content %}

{% block link %}
계정이 있으신가요?<a href="{% url 'users:main' %}">로그인</a>
{% endblock link %}

leadmanger/djangogram/djangogram/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

leadmanger/djangogram/djangogram/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}